<?php

namespace Tests\Feature;

use Illuminate\Support\Facades\Auth;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class WorkItemQATest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Auth::loginUsingId(34);
    }

    /**
     * @test
     * @runInSeparateProcess
     */
    public function qa_consultant_to_complete()
    {
        $this->withoutExceptionHandling();
        $response = $this->get('/client/work-item-qa/48');

        $response->assertStatus(200);
    }
}
